[api]
    [api.a3rt]
        [api.a3rt.talk]
        key = "KqRm3rUu4O7Q1wofoOZOhzh5TiLy2Sks"
    [api.line]
        secret = "127a5339ea9ac2fac050d8e5bda5de39"
        token="9X+fxWBO0dMiTg1/iAMinggmU6TAkgCkToC7xGLSwDWkljbzBfT6IUi7azJTUeHKt7Hhsn2JK41i1cdV9fzmpj+ZgaKpTjTHHHydm/lBOApYK+4UlAd1lp7vGRhuhJdeBJ/cFb2q93X49v/2lLNcBQdB04t89/1O/w1cDnyilFU="
        key = "AIzaSyB12JwnKf6dQSOPy_aXEGA36GoITsLlpCU"
    [api.google]
        [api.google.translate]
        key = "AIzaSyBjZOKWpXKX-n-V0reiJKgZy3SaTcGfyVo"
    [api.weather]
        key = "ba4149c91784f1280af3b91f59a4ba56"


